biblioteca_gba = {
    "A001":	"ATV - Quad Power Racing (USA, Europe)",
    "A002": "ATV - Thunder Ridge Riders (USA)",
    "A003": "Ace Combat Advance (USA, Europe)",
    "A004": "Activision Anthology (USA)",
    "A005": "Advance Guardian Heroes (USA)",
    "A006": "Advance Wars (USA) (Rev 1)",
    "A007": "Advance Wars 2 - Black Hole Rising (USA)",
    "A008": "Adventures of Jimmy Neutron Boy Genius, The - Attack of the Twonkies (USA, Europe)",
    "A009": "Adventures of Jimmy Neutron Boy Genius, The - Jet Fusion (USA, Europe)",
    "A010": "Adventures of Jimmy Neutron Boy Genius vs. Jimmy Negatron, The (USA, Europe)",
    "A011": "Aero the Acro-Bat - Rascal Rival Revenge (USA)",
    "A012": "Agassi Tennis Generation (USA)",
    "A013": "Aggressive Inline (USA)",
    "A014": "AirForce Delta Storm (USA) (En,Ja,Fr,De)",
    "A015": "Aladdin (USA) (En,Fr,De,Es)",
    "A016": "Alex Rider - Stormbreaker (USA)",
    "A017": "Alienators - Evolution Continues (USA, Europe)",
    "A018": "All-Star Baseball 2003 (USA)",
    "A019": "All-Star Baseball 2004 Featuring Derek Jeter (USA)",
    "A020": "All Grown Up! - Express Yourself (USA, Europe)",
    "A021": "Altered Beast - Guardian of the Realms (USA)",
    "A022": "Amazing Virtual Sea-Monkeys, The (USA)",
    "A023": "American Bass Challenge (USA)",
    "A024": "American Dragon - Jake Long - Rise of the Huntsclan (USA, Europe) (En,Fr,De,Es,It)",
    "A025": "American Idol (USA)",
    "A026": "American Tail, An - Fievel's Gold Rush (USA) (En,Es)",
    "A027": "Animal Snap - Rescue Them 2 by 2 (USA)",
    "A028": "Ant Bully, The (USA) (En,Fr)",
    "A029": "Antz - Extreme Racing (USA)",
    "A030": "Archer Maclean's 3D Pool (USA)",
    "A031": "Arctic Tale (USA)",
    "A032": "Army Men - Operation Green (USA) (En,Fr,De,Es,It)",
    "A033": "Army Men - Turf Wars (USA)",
    "A034": "Army Men Advance (USA, Europe) (En,Fr,De,Es,It)",
    "A035": "Around the World in 80 Days (USA)",
    "A036": "Arthur and the Invisibles (USA) (En,Fr,Es)",
    "A037": "Astro Boy - Omega Factor (USA) (En,Ja,Fr,De,Es,It)",
    "A038": "Atari Anniversary Advance (USA)",
    "A039": "Atlantis - The Lost Empire (USA, Europe)",
    "A040": "Atomic Betty (USA, Europe)",
    "A041": "Avatar - The Last Airbender (USA)",
    "A042": "Avatar - The Last Airbender - The Burning Earth (USA)",
    "B001": "BMX Trick Racer (USA)",
    "B002": "Babar to the Rescue (USA) (En,Fr,Es)",
    "B003": "Back Track (USA, Europe)",
    "B004": "Back to Stone (USA) (En,Fr)",
    "B005": "Backyard Baseball (USA)",
    "B006": "Backyard Baseball 2006 (USA)",
    "B007": "Backyard Basketball (USA)",
    "B008": "Backyard Football (USA)",
    "B009": "Backyard Football 2006 (USA)",
    "B010": "Backyard Hockey (USA)",
    "B011": "Backyard Skateboarding (USA)",
    "B012": "Backyard Sports - Baseball 2007 (USA)",
    "B013": "Backyard Sports - Basketball 2007 (USA)",
    "B014": "Backyard Sports - Football 2007 (USA)",
    "B015": "Baldur's Gate - Dark Alliance (USA)",
    "B016": "Ballistic - Ecks vs. Sever (USA)",
    "B017": "Ban    jo-Kazooie - Grunty's Revenge (USA, Europe)",
    "B018": "Banjo-Pilot (USA)",
    "B019": "Barbie - The Princess and the Pauper (USA)",
    "B020": "Barbie Diaries, The - High School Mystery (USA)",
    "B021": "Barbie Groovy Games (USA)",
    "B022": "Barbie Horse Adventures - Blue Ribbon Race (USA)",
    "B023": "Barbie Superpack - Secret Agent + Groovy Games (USA)",
    "B024": "Barbie and the Magic of Pegasus (USA)",
    "B025": "Barbie as the Island Princess (USA)",
    "B026": "Barbie in the 12 Dancing Princesses (USA)",
    "B027": "Barnyard (USA)",
    "B028": "Baseball Advance (USA)",
    "B029": "Batman - Rise of Sin Tzu (USA) (En,Fr,Es)",
    "B030": "Batman - Vengeance (USA) (En,Fr,Es)",
    "B031": "Batman Begins (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "B032": "Battle B-Daman (USA)",
    "B033": "Battle B-Daman - Fire Spirits! (USA)",
    "B034": "BattleBots - Beyond the BattleBox (USA)",
    "B035": "BattleBots - Design & Destroy (USA)",
    "B036": "Bee Game, The (USA)",
    "B037": "Berenstain Bears and the Spooky Old Tree, The (USA)",
    "B038": "Beyblade G-Revolution (USA)",
    "B039": "Beyblade V-Force - Ultimate Blader Jam (USA)",
    "B040": "Bible Game, The (USA)",
    "B041": "Big Mutha Truckers (USA)",
    "B042": "Bionicle (USA)",
    "B043": "Bionicle - Matoran Adventures (USA, Europe) (En,Fr,De,Es,It,Nl,Sv,Da)",
    "B044": "Bionicle - Maze of Shadows (USA)",
    "B045": "Bionicle Heroes (USA) (En,Fr,De,Es,It,Da)",
    "B046": "Blackthorne (USA)",
    "B047": "Blades of Thunder (USA)",
    "B048": "Blender Bros. (USA)",
    "B049": "Board Game Classics (USA)",
    "B050": "Boktai - The Sun Is in Your Hand (USA)",
    "B051": "Boktai 2 - Solar Boy Django (USA)",
    "B052": "Bomberman Max 2 - Blue Advance (USA)",
    "B053": "Bomberman Max 2 - Red Advance (USA)",
    "B054": "Bomberman Tournament (USA, Europe)",
    "B055": "Bookworm (USA)",
    "B056": "Boulder Dash EX (USA)",
    "B057": "Boxing Fever (USA, Europe)",
    "B058": "Bratz (USA) (En,Fr,Es)",
    "B059": "Bratz - Babyz (USA)",
    "B060": "Bratz - Forever Diamondz (USA)",
    "B061": "Bratz - Rock Angelz (USA, Europe)",
    "B062": "Bratz - The Movie (USA)",
    "B063": "Breath of Fire (USA)",
    "B064": "Breath of Fire II (USA)",
    "B065": "Britney's Dance Beat (USA)",
    "B066": "Broken Sword - The Shadow of the Templars (USA) (En,Fr,De,Es,It)",
    "B067": "Brother Bear (USA)",
    "B068": "Bruce Lee - Return of the Legend (USA)",
    "B069": "Bubble Bobble - Old & New (USA)",
    "B070": "Buffy the Vampire Slayer - Wrath of the Darkhul King (USA, Europe)",
    "B071": "Butt-Ugly Martians - B.K.M. Battles (USA)",
    "C001": "CIMA - The Enemy (USA)",
    "C002": "CT Special Forces (USA) (En,Fr,De,Es,It,Nl)",
    "C003": "CT Special Forces 2 - Back in the Trenches (USA) (En,Fr,De,Es,It,Nl)",
    "C004": "Cabbage Patch Kids - The Patch Puppy Rescue (USA)",
    "C005": "Cabela's Big Game Hunter (USA)",
    "C006": "Cabela's Big Game Hunter - 2005 Adventures (USA, Europe)",
    "C007": "Caesars Palace Advance - Millennium Gold Edition (USA, Europe)",
    "C008": "Camp Lazlo - Leaky Lake Games (USA)",
    "C009": "Capcom Classics Mini Mix (USA)",
    "C010": "Car Battler Joe (USA)",
    "C011": "Care Bears - The Care Quests (USA) (En,Fr,Es)",
    "C012": "Cars (USA, Europe)",
    "C013": "Cars - Mater-National Championship (USA) (En,Fr)",
    "C014": "Cartoon Network Block Party (USA)",
    "C015": "Cartoon Network Speedway (USA)",
    "C016": "Casper (USA) (En,Fr,Es)",
    "C017": "Castlevania - Aria of Sorrow (USA)",
    "C018": "Castlevania - Circle of the Moon (USA)",
    "C019": "Castlevania - Harmony of Dissonance (USA)",
    "C020": "Castlevania Double Pack (USA)",
    "C021": "Cat in the Hat, The (USA)",
    "C022": "Catwoman (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "C023": "Catz (USA, Europe)",
    "C024": "Chaoji Maliou 2 (China)",
    "C025": "Charlie and the Chocolate Factory (USA) (En,Fr,Es,Nl)",
    "C026": "Charlotte's Web (USA) (En,Fr,De,Es,It)",
    "C027": "Cheetah Girls, The (USA)",
    "C028": "Chessmaster (USA)",
    "C029": "Chicken Little (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "C030": "Chicken Shoot (USA)",
    "C031": "Chicken Shoot 2 (USA)",
    "C032": "Chronicles of Narnia, The - The Lion, the Witch and the Wardrobe (USA, Europe) (En,Fr,De,Es,It,Nl,Sv,Da)",
    "C033": "ChuChu Rocket! (USA) (En,Ja,Fr,De,Es)",
    "C034": "Cinderella - Magical Dreams (USA) (En,Fr,De,Es,It)",
    "C035": "Classic NES Series - Bomberman (USA, Europe)",
    "C036": "Classic NES Series - Castlevania (USA)",
    "C037": "Classic NES Series - Donkey Kong (USA, Europe)",
    "C038": "Classic NES Series - Dr. Mario (USA, Europe)",
    "C039": "Classic NES Series - Excitebike (USA, Europe)",
    "C040": "Classic NES Series - Ice Climber (USA, Europe)",
    "C041": "Classic NES Series - Metroid (USA, Europe)",
    "C042": "Classic NES Series - Pac-Man (USA, Europe)",
    "C043": "Classic NES Series - Super Mario Bros. (USA, Europe)",
    "C044": "Classic NES Series - The Legend of Zelda (USA, Europe)",
    "C045": "Classic NES Series - Xevious (USA, Europe)",
    "C046": "Classic NES Series - Zelda II - The Adventure of Link (USA, Europe)",
    "C047": "Codename - Kids Next Door - Operation S.O.D.A. (USA)",
    "C048": "Colin McRae Rally 2.0 (USA) (En,Fr,De)",
    "C049": "Columns Crown (USA)",
    "C050": "Combo Pack - Sonic Advance + Sonic Pinball Party (USA) (En,Ja,Fr,De,Es+En,Ja,Fr,De,Es,It)",
    "C051": "Contra Advance - The Alien Wars EX (USA)",
    "C052": "Corvette (USA) (En,Fr,De,Es,It)",
    "C053": "Crash & Spyro Superpack - Spyro - Season of Ice + Crash Bandicoot - The Huge Adventure (USA)",
    "C054": "Crash & Spyro Superpack - Spyro Orange - The Cortex Conspiracy + Crash Bandicoot Purple - Ripto's Rampage (USA)",
    "C055": "Crash Bandicoot - The Huge Adventure (USA)",
    "C056": "Crash Bandicoot 2 - N-Tranced (USA)",
    "C057": "Crash Bandicoot Purple - Ripto's Rampage (USA) (Rev 1)",
    "C058": "Crash Nitro Kart (USA)",
    "C059": "Crash Superpack - Crash Bandicoot 2 - N-Tranced + Crash Nitro Kart (USA)",
    "C060": "Crash of the Titans (USA) (En,Fr)",
    "C061": "Crazy Chase (USA)",
    "C062": "Crazy Taxi - Catch a Ride (USA)",
    "C063": "Crouching Tiger, Hidden Dragon (USA) (En,Fr,Es)",
    "C064": "Cruis'n Velocity (USA, Europe)",
    "C065": "Crushed Baseball (USA)",
    "C066": "Cubix - Robots for Everyone - Clash 'N Bash (USA)",
    "C067": "Curious George (USA)",
    "D001":	"DK - King of Swing (USA)",
    "D002":	"Danny Phantom - The Ultimate Enemy (USA)",
    "D003":	"Danny Phantom - Urban Jungle (USA)",
    "D004":	"Daredevil (USA, Europe)",
    "D005":	"Dark Arena (USA, Europe)",
    "D006":	"Dave Mirra Freestyle BMX 2 (USA)",
    "D007":	"Dave Mirra Freestyle BMX 3 (USA, Europe)",
    "D008":	"David Beckham Soccer (USA) (En,Es)",
    "D009":	"Davis Cup (USA) (En,Fr,De,Es,It)",
    "D010":	"Dead to Rights (USA)",
    "D011":	"Deal or No Deal (USA)",
    "D012":	"Defender (USA)",
    "D013":	"Defender of the Crown (USA)",
    "D014":	"DemiKids - Dark Version (USA)",
    "D015":	"DemiKids - Light Version (USA)",
    "D016":	"Demon Driver - Time to Burn Rubber! (USA)",
    "D017":	"Denki Blocks! (USA) (En,Es)",
    "D018":	"Desert Strike Advance (USA)",
    "D019":	"Dexter's Laboratory - Chess Challenge (USA)",
    "D020":	"Dexter's Laboratory - Deesaster Strikes! (USA) (En,Fr,De,Es,It) (Rev 1)",
    "D021":	"Digimon - Battle Spirit (USA)",
    "D022":	"Digimon - Battle Spirit 2 (USA) (En,Fr,De,Es,It)",
    "D023":	"Digimon Racing (USA) (En,Fr,De,Es,It)",
    "D024":	"Dinotopia - The Timestone Pirates (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "D025":	"Disney's Game + TV Episode - Lizzie McGuire 2 - Lizzie Diaries (USA) (En,Fr)",
    "D026":	"Disney's Party (USA, Europe) (En,Fr,De,Es,It)",
    "D027":	"Disney Princess (USA, Europe)",
    "D028":	"Disney Princess - Royal Adventure (USA)",
    "D029":	"Disney Sports - Basketball (USA)",
    "D030":	"Disney Sports - Football (USA)",
    "D031":	"Disney Sports - Motocross (USA)",
    "D032":	"Disney Sports - Skateboarding (USA)",
    "D033":	"Disney Sports - Snowboarding (USA)",
    "D034":	"Disney Sports - Soccer (USA)",
    "D035":	"Dogz (USA)",
    "D036":	"Dogz - Fashion (USA)",
    "D037":	"Dogz 2 (USA) (Rev 1)",
    "D038":	"Dokapon - Monster Hunter (USA)",
    "D039":	"Donald Duck Advance (USA)",
    "D040":	"Donkey Kong Country (USA)",
    "D041":	"Donkey Kong Country 2 (USA)",
    "D042":	"Donkey Kong Country 3 (USA)",
    "D043":	"Doom (USA, Europe)",
    "D044":	"Doom II (USA)",
    "D045":	"Dora the Explorer - Dora's World Adventure! (USA)",
    "D046":	"Dora the Explorer - Super Spies (USA)",
    "D047":	"Dora the Explorer - Super Star Adventures! (USA)",
    "D048":	"Dora the Explorer - The Search for the Pirate Pig's Treasure (USA)",
    "D049":	"Dora the Explorer Double Pack (USA)",
    "D050":	"Double Dragon Advance (USA)",
    "D051":	"Dr. Seuss' The Cat in the Hat (USA)",
    "D052":	"Dr. Sudoku (USA)",
    "D053":	"Dragon Ball - Advanced Adventure (USA)",
    "D054":	"Dragon Ball GT - Transformation (USA)",
    "D055":	"Dragon Ball Z - Buu's Fury (USA)",
    "D056":	"Dragon Ball Z - Collectible Card Game (USA)",
    "D057":	"Dragon Ball Z - Supersonic Warriors (USA)",
    "D058":	"Dragon Ball Z - Taiketsu (USA)",
    "D059":	"Dragon Ball Z - The Legacy of Goku (USA)",
    "D060":	"Dragon Ball Z - The Legacy of Goku II (USA)",
    "D061":	"Dragon Tales - Dragon Adventures (USA)",
    "D062":	"Drake & Josh (USA) (En,Fr)",
    "D063":	"Drill Dozer (USA)",
    "D064":	"Driv3r (USA)",
    "D065":	"Driven (USA) (En,Fr,De,Es,It)",
    "D066":	"Driver 2 Advance (USA)",
    "D067":	"Drome Racers (USA)",
    "D068":	"Dual Blades (USA)",
    "D069":	"Duel Masters - Kaijudo Showdown (USA)",
    "D070":	"Duel Masters - Sempai Legends (USA)",
    "D071":	"Duel Masters - Shadow of the Code (USA)",
    "D072":	"Duke Nukem Advance (USA)",
    "D073":	"Dungeons & Dragons - Eye of the Beholder (USA)",
    "D074":	"Dynasty Warriors Advance (USA)",
    "E001":	"E.T. - The Extra-Terrestrial (USA)",
    "E002":	"ESPN Final Round Golf 2002 (USA)",
    "E003":	"ESPN Great Outdoor Games - Bass 2002 (USA)",
    "E004":	"ESPN International Winter Sports 2002 (USA)",
    "E005":	"ESPN Winter X-Games Snowboarding 2002 (USA)",
    "E006":	"ESPN X-Games Skateboarding (USA)",
    "E007":	"Earthworm Jim (USA, Europe)",
    "E008":	"Earthworm Jim 2 (USA)",
    "E009":	"Ecks vs Sever (USA) (En,Fr,De,Es,It)",
    "E010":	"Ed, Edd n Eddy - Jawbreakers! (USA) (Rev 1)",
    "E011":	"Ed, Edd n Eddy - The Mis-Edventures (USA) (En,Fr)",
    "E012":	"Egg Mania (USA) (En,Fr,Es)",
    "E013":	"Elf - The Movie (USA) (En,Fr,De,Es,It)",
    "E014":	"Elf Bowling 1 & 2 (USA)",
    "E015":	"Enchanted - Once Upon Andalasia (USA) (En,Fr)",
    "E016":	"Eragon (USA)",
    "E017":	"everGirl (USA)",
    "E018":	"Extreme Ghostbusters - Code Ecto-1 (USA)",
    "E019":	"Extreme Skate Adventure (USA) (Rev 1)",
    "F001":	"F-14 Tomcat (USA, Europe)",
    "F002":	"F-Zero - GP Legend (USA)",
    "F003":	"F-Zero - Maximum Velocity (USA, Europe)",
    "F004":	"F1 2002 (USA, Europe)",
    "F005":	"F24 Stealth Fighter (USA)",
    "F006":	"FIFA Soccer 06 (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "F007":	"FIFA Soccer 07 (USA, Europe) (En,Fr,De,Es)",
    "F008":	"FIFA Soccer 2003 (USA, Europe) (En,Fr,De,Es,It)",
    "F009":	"FIFA Soccer 2004 (USA, Europe) (En,Fr,De,Es,It)",
    "F010":	"FIFA Soccer 2005 (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "F011":	"Fairly OddParents!, The - Breakin' da Rules (USA)",
    "F012":	"Fairly OddParents!, The - Clash with the Anti-World (USA)",
    "F013":	"Fairly OddParents!, The - Enter the Cleft (USA)",
    "F014":	"Fairly OddParents!, The - Shadow Showdown (USA)",
    "F015":	"Family Feud (USA)",
    "F016":	"Fantastic 4 (USA)",
    "F017":	"Fantastic 4 - Flame On (USA)",
    "F018":	"Fear Factor Unleashed (USA)",
    "F019":	"Final Fantasy I & II - Dawn of Souls (USA)",
    "F020":	"Final Fantasy IV Advance (USA)",
    "F021":	"Final Fantasy Tactics Advance (USA)",
    "F022":	"Final Fantasy V Advance (USA)",
    "F023":	"Final Fantasy VI Advance (USA)",
    "F024":	"Final Fight One (USA)",
    "F025":	"Finding Nemo (USA, Europe)",
    "F026":	"Finding Nemo - The Continuing Adventures (USA, Europe)",
    "F027":	"Fire Emblem (USA, Australia)",
    "F028":	"Fire Emblem - The Sacred Stones (USA, Australia)",
    "F029":	"Fire Pro Wrestling (USA, Europe)",
    "F030":	"Fire Pro Wrestling 2 (USA)",
    "F031":	"Flintstones, The - Big Trouble in Bedrock (USA)",
    "F032":	"Flushed Away (USA)",
    "F033":	"Ford Racing 3 (USA)",
    "F034":	"Fortress (USA, Europe)",
    "F035":	"Foster's Home for Imaginary Friends (USA)",
    "F036":	"Franklin's Great Adventures (USA) (En,Fr,Es)",
    "F037":	"Franklin the Turtle (USA) (En,Fr,De,Es,It,Sv,No,Da,Fi)",
    "F038":	"Freekstyle (USA)",
    "F039":	"Frogger's Adventures - Temple of the Frog (USA) (En,Fr,De,Es,It)",
    "F040":	"Frogger's Adventures 2 - The Lost Wand (USA) (En,Es)",
    "F041":	"Frogger's Journey - The Forgotten Relic (USA)",
    "F042":	"Frogger Advance - The Great Quest (USA)",
    "G001":	"GT Advance - Championship Racing (USA, Europe)",
    "G002":	"GT Advance 2 - Rally Racing (USA)",
    "G003":	"GT Advance 3 - Pro Concept Racing (USA)",
    "G004":	"Gadget Racers (USA)",
    "G005":	"Galidor - Defenders of the Outer Dimension (USA) (En,Fr,De,Es,It,Nl,Sv,Da)",
    "G006":	"Game & Watch Gallery 4 (USA)",
    "G007":	"Games Explosion! (USA)",
    "G008":	"Garfield - The Search for Pooky (USA) (En,Fr,De,Es,It)",
    "G009":	"Garfield and His Nine Lives (USA) (En,Fr,Es)",
    "G010":	"Gauntlet - Dark Legacy (USA)",
    "G011":	"Gekido Advance - Kintaro's Revenge (USA)",
    "G012":	"Gem Smashers (USA)",
    "G013":	"Ghost Rider (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "G014":	"Global Star - Sudoku Fever (USA)",
    "G015":	"Godzilla - Domination! (USA)",
    "G016":	"Golden Nugget Casino (USA, Europe)",
    "G017":	"Golden Sun (USA, Europe)",
    "G018":	"Golden Sun - The Lost Age (USA, Europe)",
    "G019":	"Gradius Galaxies (USA)",
    "G020":	"Grand Theft Auto Advance (USA)",
    "G021":	"Green Eggs and Ham by Dr. Seuss (USA)",
    "G022":	"Greg Hastings' Tournament Paintball Max'd (USA)",
    "G023":	"Gremlins - Stripe vs Gizmo (USA)",
    "G024":	"Grim Adventures of Billy & Mandy, The (USA)",
    "G025":	"Guilty Gear X - Advance Edition (USA)",
    "G026":	"Gumby vs. the Astrobots (USA)",
    "G027":	"Gunstar Super Heroes (USA)",
    "H001":	"Hamtaro - Ham-Ham Heartbreak (USA)",
    "H002":	"Happy Feet (USA) (En,Fr)",
    "H003":	"Hardcore Pinball (USA, Europe)",
    "H004":	"Harlem Globetrotters - World Tour (USA)",
    "H005":	"Harry Potter - Quidditch World Cup (USA, Europe) (En,Fr,De,Es,It,Nl,Da)",
    "H006":	"Harry Potter and the Chamber of Secrets (USA, Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da)",
    "H007":	"Harry Potter and the Goblet of Fire (USA, Europe) (En,Fr,De,Es,It,Nl,Da)",
    "H008":	"Harry Potter and the Order of the Phoenix (USA, Europe) (En,Fr,De,Es,It,Nl,Da)",
    "H009":	"Harry Potter and the Prisoner of Azkaban (USA, Europe) (En,Fr,De,Es,It,Nl,Da)",
    "H010":	"Harry Potter and the Sorcerer's Stone (USA, Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da)",
    "H011":	"Harvest Moon - Friends of Mineral Town (USA)",
    "H012":	"Harvest Moon - More Friends of Mineral Town (USA)",
    "H013":	"Hello Kitty - Happy Party Pals (USA)",
    "H014":	"Herbie - Fully Loaded (USA)",
    "H015":	"Hey Arnold! - The Movie (USA)",
    "H016":	"Hi Hi Puffy AmiYumi - Kaznapped! (USA)",
    "H017":	"High Heat Major League Baseball 2002 (USA, Europe)",
    "H018":	"High Heat Major League Baseball 2003 (USA)",
    "H019":	"High School Musical - Livin' the Dream (USA)",
    "H020":	"Hobbit, The - The Prelude to the Lord of the Rings (USA)",
    "H021":	"Home on the Range (USA) (En,Fr)",
    "H022":	"Horsez (USA)",
    "H023":	"Hot Potato! (USA)",
    "H024":	"Hot Wheels - All Out (USA)",
    "H025":	"Hot Wheels - Burnin' Rubber (USA)",
    "H026":	"Hot Wheels - Stunt Track Challenge (USA, Europe)",
    "H027":	"Hot Wheels - Velocity X (USA)",
    "H028":	"Hot Wheels - World Race (USA)",
    "H029":	"Hugo - The Evil Mirror Advance (USA) (En,Fr,Es)",
    "I001":	"I Spy Challenger! (USA)",
    "I002":	"Ice Age (USA) (En,Fr,Es)",
    "I003":	"Ice Age 2 - The Meltdown (USA)",
    "I004":	"Ice Nine (USA, Europe) (En,Fr,De,Es,It)",
    "I005":	"Incredible Hulk, The (USA)",
    "I006":	"Incredibles, The (USA, Europe)",
    "I007":	"Incredibles, The - Rise of the Underminer (USA, Europe)",
    "I008":	"Inspector Gadget - Advance Mission (USA)",
    "I009":	"International Karate Plus (USA)",
    "I010":	"Invincible Iron Man, The (USA, Europe)",
    "I011":	"Iridion 3D (USA, Europe)",
    "I012":	"Iridion II (USA)",
    "I013":	"Island Xtreme Stunts (USA, Europe) (En,Fr,De,Es,It,Nl,Sv,Da)",
    "I014":	"It's Mr. Pants (USA, Europe)",
    "J001":	"Jackie Chan Adventures - Legend of the Dark Hand (USA, Europe)",
    "J002":	"James Pond - Codename Robocod (USA) (En,Fr,Es,Pt)",
    "J003":	"Jazz Jackrabbit (USA, Europe)",
    "J004":	"Jet Grind Radio (USA)",
    "J005":	"Jimmy Neutron Boy Genius (USA)",
    "J006":	"Jonny Moseley Mad Trix (USA, Europe) (En,Fr,De,Es,It)",
    "J007":	"Juka and the Monophonic Menace (USA) (En,Fr,Es)",
    "J008":	"Jungle Book, The (USA) (En,Fr,De,Es,It,Nl)",
    "J009":	"Jurassic Park III - Island Attack (USA)",
    "J010":	"Jurassic Park III - Park Builder (USA)",
    "J011":	"Jurassic Park III - The DNA Factor (USA)",
    "J012":	"Justice League - Chronicles (USA)",
    "J013":	"Justice League - Injustice for All (USA)",
    "J014":	"Justice League Heroes - The Flash (USA)",
    "K001":	"Kao the Kangaroo (USA) (En,Fr,De,Es,It,Nl)",
    "K002":	"Karnaaj Rally (USA, Europe)",
    "K003":	"Kelly Slater's Pro Surfer (USA, Europe)",
    "K004":	"Kid's Cards (USA)",
    "K005":	"Kill Switch (USA)",
    "K006":	"Killer 3D Pool (USA)",
    "K007":	"Kim Possible - Revenge of Monkey Fist (USA)",
    "K008":	"Kim Possible 2 - Drakken's Demise (USA) (En,Fr)",
    "K009":	"Kim Possible 3 - Team Possible (USA) (En,Fr)",
    "K010":	"Kingdom Hearts - Chain of Memories (USA)",
    "K011":	"King of Fighters EX, The - NeoBlood (USA) (Rev 1)",
    "K012":	"King of Fighters EX 2, The - Howling Blood (USA)",
    "K013":	"Kirby & The Amazing Mirror (USA)",
    "K014":	"Kirby - Nightmare in Dream Land (USA)",
    "K015":	"Klonoa - Empire of Dreams (USA)",
    "K016":	"Klonoa 2 - Dream Champ Tournament (USA)",
    "K017":	"Knights' Kingdom (USA)",
    "K018":	"Koala Brothers - Outback Adventures (USA) (En,Fr,De,Es,It,Nl,Pt,Da)",
    "K019":	"Konami Collector's Series - Arcade Advanced (USA)",
    "K020":	"Konami Krazy Racers (USA)",
    "K021":	"Kong - King of Atlantis (USA)",
    "K022":	"Kong - The 8th Wonder of the World (USA) (En,Fr,Es)",
    "K023":	"Kong - The Animated Series (USA) (En,Fr,De,Es,It,Nl)",
    "L001":	"LEGO Bionicle (USA) (En,Fr)",
    "L002":	"LEGO Island 2 - The Brickster's Revenge (USA) (En,Fr)",
    "L003":	"LEGO Racers 2 (USA) (En,Fr)",
    "L004":	"LEGO Soccer Mania (USA, Europe) (En,Fr,De,Es,It,Nl,Sv,Da)",
    "L005":	"LEGO Star Wars - The Video Game (USA, Europe) (En,Fr,De,Es,It,Nl,Da)",
    "L006":	"LEGO Star Wars II - The Original Trilogy (USA)",
    "L007":	"Lady Sia (USA) (En,Fr,De,Es,It,Nl)",
    "L008":	"Land Before Time, The (USA) (En,Es)",
    "L009":	"Land Before Time, The - Into the Mysterious Beyond (USA) (En,Fr,Es)",
    "L010":	"Lara Croft Tomb Raider - Legend (USA) (En,Fr,De,Es,It)",
    "L011":	"Lara Croft Tomb Raider - The Prophecy (USA) (En,Fr,De,Es,It)",
    "L012":	"Legend of Spyro, The - A New Beginning (USA)",
    "L013":	"Legend of Spyro, The - The Eternal Night (USA) (En,Fr)",
    "L014":	"Legend of Zelda, The - A Link to the Past & Four Swords (USA)",
    "L015":	"Legend of Zelda, The - The Minish Cap (USA)",
    "L016":	"Legends of Wrestling II (USA, Europe)",
    "L017":	"Lemony Snicket's A Series of Unfortunate Events (USA, Europe)",
    "L018":	"Let's Ride! - Dreamer (USA)",
    "L019":	"Let's Ride! - Friends Forever (USA)",
    "L020":	"Let's Ride! - Sunshine Stables (USA)",
    "L021":	"Lilo & Stitch (USA)",
    "L022":	"Lilo & Stitch 2 - Haemsterviel Havoc (USA)",
    "L023":	"Lion King 1 1-2, The (USA)",
    "L024":	"Little Einsteins (USA)",
    "L025":	"Little League Baseball 2002 (USA) (En,Es)",
    "L026":	"Little Mermaid, The - Magic in Two Kingdoms (USA, Europe) (En,Fr,De,Es,It)",
    "L027":	"Lizzie McGuire - On the Go! (USA)",
    "L028":	"Lizzie McGuire 2 - Lizzie Diaries (USA) (En,Fr)",
    "L029":	"Lizzie McGuire 3 - Homecoming Havoc (USA)",
    "L030":	"Looney Tunes - Back in Action (USA, Europe) (En,Fr,De,Es,It)",
    "L031":	"Looney Tunes Double Pack (USA)",
    "L032":	"Lord of the Rings, The - The Fellowship of the Ring (USA) (Rev 1)",
    "L033":	"Lord of the Rings, The - The Return of the King (USA, Europe) (En,Fr,De,Es,It)",
    "L034":	"Lord of the Rings, The - The Third Age (USA, Europe) (En,Fr,De,Es,It)",
    "L035":	"Lord of the Rings, The - The Two Towers (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "L036":	"Lost Vikings, The (USA)",
    "L037":	"Lufia - The Ruins of Lore (USA)",
    "L038":	"Lunar Legend (USA)",
    "M001": "M&M's - Blast! (USA)",
    "M002": "M&M's - Break' Em (USA) (Rev 1)",
    "M003": "MLB SlugFest 20-04 (USA)",
    "M004": "MX 2002 Featuring Ricky Carmichael (USA, Europe)",
    "M005": "Madagascar (USA)",
    "M006": "Madagascar - Operation Penguin (USA)",
    "M007": "Madden NFL 06 (USA)",
    "M008": "Madden NFL 07 (USA)",
    "M009": "Madden NFL 2002 (USA)",
    "M010": "Madden NFL 2003 (USA)",
    "M011": "Madden NFL 2004 (USA)",
    "M012": "Madden NFL 2005 (USA)",
    "M013": "Magical Quest 2 Starring Mickey & Minnie (USA) (En,Fr,De)",
    "M014": "Magical Quest 3 Starring Mickey & Donald (USA) (En,Fr,De)",
    "M015": "Magical Quest Starring Mickey & Minnie (USA)",
    "M016": "Majesco's Sports Pack (USA)",
    "M017": "March of the Penguins (USA)",
    "M018": "Mario & Luigi - Superstar Saga (USA)",
    "M019": "Mario Golf - Advance Tour (USA)",
    "M020": "Mario Kart - Super Circuit (USA)",
    "M021": "Mario Party Advance (USA)",
    "M022": "Mario Pinball Land (USA, Australia)",
    "M023": "Mario Tennis - Power Tour (USA, Australia) (En,Fr,De,Es,It)",
    "M024": "Mario vs. Donkey Kong (USA, Australia)",
    "M025": "Marvel - Ultimate Alliance (USA)",
    "M026": "Mary-Kate and Ashley - Girls Night Out (USA, Europe)",
    "M027": "Mary-Kate and Ashley - Sweet 16 - Licensed to Drive (USA, Europe)",
    "M028": "Masters of the Universe - He-Man - Power of Grayskull (USA)",
    "M029": "Mat Hoffman's Pro BMX (USA, Europe)",
    "M030": "Mat Hoffman's Pro BMX 2 (USA, Europe)",
    "M031": "Matchbox Cross Town Heroes (USA)",
    "M032": "Math Patrol - The Kleptoid Threat (USA)",
    "M033": "Max Payne (USA)",
    "M034": "Mazes of Fate (USA) (En,Fr,De,Es,It)",
    "M035": "Mech Platoon (USA)",
    "M036": "Medabots - Metabee (USA)",
    "M037": "Medabots - Rokusho (USA)",
    "M038": "Medabots AX - Metabee Ver. (USA)",
    "M039": "Medabots AX - Rokusho Ver. (USA)",
    "M040": "Medal of Honor - Infiltrator (USA, Europe) (En,Fr,De)",
    "M041": "Medal of Honor - Underground (USA)",
    "M042": "Meet the Robinsons (USA)",
    "M043": "Mega Man & Bass (USA)",
    "M044": "Mega Man Battle Chip Challenge (USA)",
    "M045": "Mega Man Battle Network (USA)",
    "M046": "Mega Man Battle Network 2 (USA)",
    "M047": "Mega Man Battle Network 3 - Blue Version (USA)",
    "M048": "Mega Man Battle Network 3 - White Version (USA)",
    "M049": "Mega Man Battle Network 4 - Blue Moon (USA)",
    "M050": "Mega Man Battle Network 4 - Red Sun (USA)",
    "M051": "Mega Man Battle Network 5 - Team Colonel (USA)",
    "M052": "Mega Man Battle Network 5 - Team Protoman (USA)",
    "M053": "Mega Man Battle Network 6 - Cybeast Falzar (USA)",
    "M054": "Mega Man Battle Network 6 - Cybeast Gregar (USA)",
    "M055": "Mega Man Zero (USA, Europe)",
    "M056": "Mega Man Zero 2 (USA)",
    "M057": "Mega Man Zero 3 (USA)",
    "M058": "Mega Man Zero 4 (USA)",
    "M059": "Men in Black - The Series (USA)",
    "M060": "Metal Slug Advance (USA)",
    "M061": "Metroid - Zero Mission (USA)",
    "M062": "Metroid Fusion (USA)",
    "M063": "Midnight Club - Street Racing (USA)",
    "M064": "Midway's Greatest Arcade Hits (USA, Europe)",
    "M065": "Mighty Beanz - Pocket Puzzles (USA)",
    "M066": "Mike Tyson Boxing (USA) (En,Fr,De,Es,It)",
    "M067": "Minority Report - Everybody Runs (USA, Europe)",
    "M068": "Mission Impossible - Operation Surma (USA) (En,Fr,Es)",
    "M069": "Mobile Suit Gundam Seed - Battle Assault (USA)",
    "M070": "Monopoly (USA)",
    "M071": "Monster! Bass Fishing (USA)",
    "M072": "Monster Force (USA)",
    "M073": "Monster House (USA) (En,Fr)",
    "M074": "Monster Jam - Maximum Destruction (USA)",
    "M075": "Monster Rancher Advance (USA)",
    "M076": "Monster Rancher Advance 2 (USA)",
    "M077": "Monster Truck Madness (USA, Europe)",
    "M078": "Monster Trucks (USA, Europe)",
    "M079": "Monster Trucks Mayhem (USA)",
    "M080": "Monsters, Inc. (USA, Europe)",
    "M081": "Mortal Kombat - Deadly Alliance (USA) (En,Fr,De,Es,It)",
    "M082": "Mortal Kombat - Tournament Edition (USA) (En,Fr,De,Es,It)",
    "M083": "Mortal Kombat Advance (USA)",
    "M084": "MotoGP (USA) (En,Fr,De,Es,It)",
    "M085": "Motocross Maniacs Advance (USA) (En,Es)",
    "M086": "Motoracer Advance (USA) (En,Fr,De,Es,It)",
    "M087": "Mr. Driller 2 (USA)",
    "M088": "Ms. Pac-Man - Maze Madness (USA)",
    "M089": "Mucha Lucha! - Mascaritas of the Lost Code (USA) (En,Fr,Es)",
    "M090": "Mummy, The (USA) (En,Fr,De,Es,It)",
    "M091": "Muppet Pinball Mayhem (USA)",
    "M092": "Muppets, The - On with the Show! (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "M093": "My Little Pony - Crystal Princess - The Runaway Rainbow (USA)",
    "N001": "NASCAR Heat 2002 (USA)",
    "N002": "NBA Jam 2002 (USA, Europe)",
    "N003": "NFL Blitz 20-02 (USA)",
    "N004": "NFL Blitz 20-03 (USA)",
    "N005": "NHL 2002 (USA)",
    "N006": "NHL Hitz 20-03 (USA)",
    "N007": "Namco Museum (USA)",
    "N008": "Namco Museum - 50th Anniversary (USA)",
    "N009": "Nancy Drew - Message in a Haunted Mansion (USA)",
    "N010": "Naruto - Ninja Council (USA)",
    "N011": "Naruto - Ninja Council 2 (USA)",
    "N012": "Need for Speed - Most Wanted (USA, Europe) (En,Fr,De,It)",
    "N013": "Need for Speed - Porsche Unleashed (USA)",
    "N014": "Need for Speed - Underground (USA, Europe) (En,Fr,De,It)",
    "N015": "Need for Speed - Underground 2 (USA, Europe) (En,Fr,De,It)",
    "N016": "Need for Speed Carbon - Own the City (USA, Europe) (En,Fr,De,Es,It)",
    "N017": "Nicktoons - Attack of the Toybots (USA)",
    "N018": "Nicktoons - Battle for Volcano Island (USA)",
    "N019": "Nicktoons - Freeze Frame Frenzy (USA)",
    "N020": "Nicktoons Racing (USA)",
    "N021": "Nicktoons Unite! (USA)",
    "N022": "Ninja Five-0 (USA)",
    "N023": "No Rules - Get Phat (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "N024": "Noddy - A Day in Toyland (USA) (En,Fr,Es)",
    "O001": "Oddworld - Munch's Oddysee (USA, Europe)",
    "O002": "One Piece (USA)",
    "O003": "Onimusha Tactics (USA)",
    "O004": "Open Season (USA) (En,Fr,Es)",
    "O005": "Operation Armored Liberty (USA)",
    "O006": "Over the Hedge (USA)",
    "O007": "Over the Hedge - Hammy Goes Nuts! (USA)",
    "O008": "Ozzy & Drix (USA)",
    "P001":	"Pac-Man Collection (USA)",
    "P002":	"Pac-Man Pinball Advance (USA)",
    "P003":	"Pac-Man World (USA)",
    "P004":	"Pac-Man World 2 (USA)",
    "P005":	"Paws & Claws - Best Friends - Dogs & Cats (USA)",
    "P006":	"Paws & Claws - Pet Resort (USA)",
    "P007":	"Paws & Claws - Pet Vet (USA)",
    "P008":	"Peter Pan - Return to Neverland (USA) (Rev 1)",
    "P009":	"Peter Pan - The Motion Picture Event (USA)",
    "P010":	"Petz - Hamsterz Life 2 (USA)",
    "P011":	"Petz Vet (USA)",
    "P012":	"Phalanx (USA)",
    "P013":	"Phantasy Star Collection (USA)",
    "P014":	"Phil of the Future (USA)",
    "P015":	"Piglet's Big Game (USA)",
    "P016":	"Pinball Tycoon (USA)",
    "P017":	"Pinball of the Dead, The (USA)",
    "P018":	"Pink Panther - Pinkadelic Pursuit (USA)",
    "P019":	"Pinobee - Wings of Adventure (USA, Europe)",
    "P020":	"Pirates of the Caribbean - Dead Man's Chest (USA, Europe) (En,Fr,De,Es,It)",
    "P021":	"Pirates of the Caribbean - The Curse of the Black Pearl (USA) (En,Fr,De,Es,It)",
    "P022":	"Pitfall - The Lost Expedition (USA)",
    "P023":	"Pitfall - The Mayan Adventure (USA, Europe)",
    "P024":	"Planet Monsters (USA) (En,Fr,De,Es,It,Nl)",
    "P025":	"Planet of the Apes (USA) (En,Fr,De,Es,It,Nl)",
    "P026":	"Pocket Dogs (USA)",
    "P027":	"Pocket Professor - Kwik Notes - Volume One (USA)",
    "P028":	"Pocky & Rocky with Becky (USA)",
    "P029":	"Pokemon - Emerald Version (USA, Europe)",
    "P030":	"Pokemon - FireRed Version (USA, Europe) (Rev 1)",
    "P031":	"Pokemon - LeafGreen Version (USA, Europe) (Rev 1)",
    "P032":	"Pokemon - Ruby Version (USA, Europe) (Rev 2)",
    "P033":	"Pokemon - Sapphire Version (USA, Europe) (Rev 2)",
    "P034":	"Pokemon Mystery Dungeon - Red Rescue Team (USA, Australia)",
    "P035":	"Pokemon Pinball - Ruby & Sapphire (USA)",
    "P036":	"Polar Express, The (USA, Europe) (En,Fr,De,Es,It)",
    "P037":	"Polarium Advance (USA)",
    "P038":	"Polly Pocket! - Super Splash Island (USA) (Vivendi)",
    "P039":	"Popeye - Rush for Spinach (USA, Europe) (En,Fr,De,Es,It)",
    "P040":	"Power Rangers - Dino Thunder (USA, Europe)",
    "P041":	"Power Rangers - Ninja Storm (USA)",
    "P042":	"Power Rangers - Time Force (USA, Europe)",
    "P043":	"Power Rangers - Wild Force (USA, Europe)",
    "P044":	"Power Rangers S.P.D. (USA, Europe)",
    "P045":	"Powerpuff Girls, The - Him and Seek (USA)",
    "P046":	"Powerpuff Girls, The - Mojo Jojo A-Go-Go (USA) (En,Fr,De,Es,It,Nl)",
    "P047":	"Prehistorik Man (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "P048":	"Prince of Persia - The Sands of Time (USA) (En,Fr,Es) (Rev 1)",
    "P049":	"Princess Natasha - Student, Secret Agent, Princess (USA)",
    "P050":	"Proud Family, The (USA)",
    "P051":	"Punch King - Arcade Boxing (USA)",
    "P052":	"Puppy Luv - Spa and Resort (USA)",
    "P053":	"Puyo Pop (USA) (En,Ja)",
    "Q001":	"Quad Desert Fury (USA, Europe)",
    "R001":	"R-Type III - The Third Lightning (USA)",
    "R002":	"Racing Gears Advance (USA)",
    "R003":	"Rampage - Puzzle Attack (USA, Europe)",
    "R004":	"Rapala Pro Fishing (USA, Europe)",
    "R005":	"Ratatouille (USA)",
    "R006":	"Rave Master - Special Attack Force! (USA)",
    "R007":	"Rayman - 10th Anniversary (USA) (En,Fr,De,Es,It)",
    "R008":	"Rayman - Hoodlum's Revenge (USA) (En,Fr,Es)",
    "R009":	"Rayman - Raving Rabbids (USA) (En,Fr,Es)",
    "R010":	"Rayman 3 (USA) (En,Fr,Es)",
    "R011":	"Rayman Advance (USA) (En,Fr,De,Es,It)",
    "R012":	"Razor Freestyle Scooter (USA)",
    "R013":	"Ready 2 Rumble Boxing - Round 2 (USA)",
    "R014":	"Rebelstar - Tactical Command (USA)",
    "R015":	"Reign of Fire (USA) (En,Fr,De,Es,It)",
    "R016":	"Rescue Heroes - Billy Blazes! (USA)",
    "R017":	"Revenge of Shinobi, The (USA)",
    "R018":	"Ripping Friends, The - The World's Most Manly Men! (USA, Europe)",
    "R019":	"River City Ransom EX (USA)",
    "R020":	"Riviera - The Promised Land (USA)",
    "R021":	"Road Rash - Jailbreak (USA)",
    "R022":	"Robopon 2 - Cross Version (USA)",
    "R023":	"Robopon 2 - Ring Version (USA)",
    "R024":	"Robot Wars - Advanced Destruction (USA)",
    "R025":	"Robotech - The Macross Saga (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "R026":	"Robots (USA)",
    "R027":	"Rock 'N Roll Racing (USA)",
    "R028":	"Rock'em Sock'em Robots (USA)",
    "R029":	"Rocket Power - Beach Bandits (USA, Europe)",
    "R030":	"Rocket Power - Dream Scheme (USA, Europe)",
    "R031":	"Rocket Power - Zero Gravity Zone (USA)",
    "R032":	"Rocky (USA) (En,Fr,De,Es,It)",
    "R033":	"Rugrats - Castle Capers (USA, Europe)",
    "R034":	"Rugrats - Go Wild (USA, Europe)",
    "R035":	"Rugrats - I Gotta Go Party (USA, Europe)",
    "S001": "SD Gundam Force (USA)",
    "S002": "SEGA Arcade Gallery (USA)",
    "S003": "SEGA Rally Championship (USA)",
    "S004": "SEGA Smash Pack (USA)",
    "S005": "SSX 3 (USA, Europe)",
    "S006": "SSX Tricky (USA, Europe) (En,Fr,De)",
    "S007": "Sabre Wulf (USA)",
    "S008": "Sabrina the Teenage Witch - Potion Commotion (USA) (En,Fr,Es)",
    "S009": "Salt Lake 2002 (USA) (En,Fr,De,Es,It,Nl)",
    "S010": "Samurai Deeper Kyo (USA)",
    "S011": "Samurai Jack - The Amulet of Time (USA, Europe)",
    "S012": "Santa Clause 3, The - The Escape Clause (USA)",
    "S013": "Scooby-Doo! - Mystery Mayhem (USA) (En,Fr)",
    "S014": "Scooby-Doo! - Unmasked (USA) (En,Fr)",
    "S015": "Scooby-Doo (USA)",
    "S016": "Scooby-Doo 2 - Monsters Unleashed (USA, Europe)",
    "S017": "Scooby-Doo and the Cyber Chase (USA, Europe)",
    "S018": "Scorpion King, The - Sword of Osiris (USA)",
    "S019": "Scrabble Blast! (USA)",
    "S020": "Scurge - Hive (USA) (En,Fr,Es)",
    "S021": "Sea Trader - Rise of Taipan (USA)",
    "S022": "Secret Agent Barbie - Royal Jewels Mission (USA)",
    "S023": "Serious Sam Advance (USA) (En,Fr,De)",
    "S024": "Shaman King - Legacy of the Spirits - Soaring Hawk (USA)",
    "S025": "Shaman King - Legacy of the Spirits - Sprinting Wolf (USA)",
    "S026": "Shaman King - Master of Spirits (USA)",
    "S027": "Shaman King - Master of Spirits 2 (USA)",
    "S028": "Shamu's Deep Sea Adventures (USA)",
    "S029": "Shark Tale (USA, Europe)",
    "S030": "Shaun Palmer's Pro Snowboarder (USA, Europe)",
    "S031": "Shifting Gears - Road Trip (USA)",
    "S032": "Shining Force - Resurrection of the Dark Dragon (USA)",
    "S033": "Shining Soul (USA)",
    "S034": "Shining Soul II (USA)",
    "S035": "Shrek - Hassle at the Castle (USA) (En,Fr,De,Es,It,Nl)",
    "S036": "Shrek - Reekin' Havoc (USA) (En,Fr,De,Es,It,Nl)",
    "S037": "Shrek - Smash n' Crash Racing (USA)",
    "S038": "Shrek - Super Slam (USA)",
    "S039": "Shrek - Swamp Kart Speedway (USA) (En,Fr,De,Es,It,Nl) (Rev 1)",
    "S040": "Shrek 2 (USA, Europe)",
    "S041": "Shrek 2 - Beg for Mercy (USA, Europe)",
    "S042": "Shrek the Third (USA)",
    "S043": "Sigma Star Saga (USA, Europe)",
    "S044": "Silent Scope (USA) (En,Fr,De,Es,It)",
    "S045": "SimCity 2000 (USA) (Rev 1)",
    "S046": "Simpsons, The - Road Rage (USA, Europe)",
    "S047": "Sims, The - Bustin' Out (USA) (En,Fr,De,Es,It,Nl) (Rev 1)",
    "S048": "Sims 2, The (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "S049": "Sims 2, The - Pets (USA, Europe)",
    "S050": "Sitting Ducks (USA) (En,Fr,De,Es,It,Nl)",
    "S051": "Sky Dancers - They Magically Fly! (USA)",
    "S052": "Smashing Drive (USA)",
    "S053": "Smuggler's Run (USA)",
    "S054": "Snood (USA)",
    "S055": "Snood 2 - On Vacation (USA)",
    "S056": "Soccer Kid (USA, Europe)",
    "S057": "Sonic Advance (USA) (En,Ja)",
    "S058": "Sonic Advance 2 (USA) (En,Ja,Fr,De,Es,It)",
    "S059": "Sonic Advance 3 (USA) (En,Ja,Fr,De,Es,It)",
    "S060": "Sonic Battle (USA) (En,Ja,Fr,De,Es,It)",
    "S061": "Sonic Pinball Party (USA) (En,Ja,Fr,De,Es,It)",
    "S062": "Sonic The Hedgehog - Genesis (USA)",
    "S063": "Sound of Thunder, A (USA) (En,Fr,De,Es,It)",
    "S064": "Space Channel 5 - Ulala's Cosmic Attack (USA)",
    "S065": "Space Invaders (USA, Europe)",
    "S066": "Spider-Man (USA, Europe)",
    "S067": "Spider-Man - Battle for New York (USA)",
    "S068": "Spider-Man - Mysterio's Menace (USA, Europe)",
    "S069": "Spider-Man 2 (USA, Europe)",
    "S070": "Spider-Man 3 (USA)",
    "S071": "Spirit - Stallion of the Cimarron - Search for Homeland (USA)",
    "S072": "Spirits & Spells (USA)",
    "S073": "SpongeBob's Atlantis SquarePantis (USA)",
    "S074": "SpongeBob SquarePants - Battle for Bikini Bottom (USA)",
    "S075": "SpongeBob SquarePants - Creature from the Krusty Krab (USA)",
    "S076": "SpongeBob SquarePants - Lights, Camera, Pants! (USA)",
    "S077": "SpongeBob SquarePants - Revenge of the Flying Dutchman (USA, Europe)",
    "S078": "SpongeBob SquarePants - SuperSponge (USA, Europe)",
    "S079": "SpongeBob SquarePants Movie, The (USA)",
    "S080": "Sports Illustrated for Kids - Baseball (USA)",
    "S081": "Sports Illustrated for Kids - Football (USA)",
    "S082": "Sportsmans Pack 2 in 1 - Cabela's Big Game Hunter + Rapala Pro Fishing (USA)",
    "S083": "Spy Hunter (USA) (En,Ja,Fr,De,Es)",
    "S084": "Spy Kids 3-D - Game Over (USA)",
    "S085": "Spy Kids Challenger (USA)",
    "S086": "Spy Muppets - License to Croak (USA) (En,Fr,De,Es,It,Nl)",
    "S087": "Spyro - Attack of the Rhynocs (USA)",
    "S088": "Spyro - Season of Ice (USA)",
    "S089": "Spyro 2 - Season of Flame (USA)",
    "S090": "Spyro Orange - The Cortex Conspiracy (USA) (Rev 1)",
    "S091": "Spyro Superpack - Spyro - Season of Ice + Spyro 2 - Season of Flame (USA)",
    "S092": "Stadium Games (USA)",
    "S093": "Star Wars - Episode II - Attack of the Clones (USA)",
    "S094": "Star Wars - Episode III - Revenge of the Sith (USA) (En,Fr,Es)",
    "S095": "Star Wars - Flight of the Falcon (USA)",
    "S096": "Star Wars - Jedi Power Battles (USA)",
    "S097": "Star Wars - The New Droid Army (USA)",
    "S098": "Star Wars Trilogy - Apprentice of the Force (USA) (En,Fr,Es)",
    "S099": "Star X (USA) (En,Fr,De,Es,It,Nl)",
    "S100": "Starsky & Hutch (USA)",
    "S101": "Strawberry Shortcake - Summertime Adventure (USA)",
    "S102": "Strawberry Shortcake - Summertime Adventure - Special Edition (USA)",
    "S103": "Strawberry Shortcake - Sweet Dreams (USA)",
    "S104": "Street Fighter Alpha 3 (USA)",
    "S105": "Street Jam Basketball (USA, Europe)",
    "S106": "Street Racing Syndicate (USA)",
    "S107": "Strike Force Hydra (USA)",
    "S108": "Stuart Little 2 (USA, Europe)",
    "S109": "Stuntman (USA) (En,Fr,Es)",
    "S110": "Suite Life of Zack & Cody, The - Tipton Caper (USA) (En,Fr)",
    "S111": "Summon Night - Swordcraft Story (USA)",
    "S112": "Summon Night - Swordcraft Story 2 (USA)",
    "S113": "Sum of All Fears, The (USA) (En,Fr,De,Es,It)",
    "S114": "Super Army War (USA)",
    "S115": "Super Bubble Pop (USA)",
    "S116": "Super Bust-A-Move (USA) (En,Fr,Es)",
    "S117": "Super Collapse! II (USA)",
    "S118": "Super Dodge Ball Advance (USA) (Rev 1)",
    "S119": "Super Dropzone - Intergalactic Rescue Mission (USA)",
    "S120": "Super Duper Sumos (USA)",
    "S121": "Super Ghouls'n Ghosts (USA, Europe)",
    "S122": "Super Hornet FA 18F (USA, Europe)",
    "S123": "Super Mario Advance (USA, Europe)",
    "S124": "Super Mario Advance 2 - Super Mario World (USA, Australia)",
    "S125": "Super Mario Advance 3 - Yoshi's Island (USA)",
    "S126": "Super Mario Advance 4 - Super Mario Bros. 3 (USA) (Rev 1) (Virtual Console)",
    "S127": "Super Monkey Ball Jr. (USA)",
    "S128": "Super Puzzle Fighter II (USA) (Rev 1)",
    "S129": "Super Robot Taisen - Original Generation (USA)",
    "S130": "Super Robot Taisen - Original Generation 2 (USA)",
    "S131": "Super Street Fighter II Turbo - Revival (USA)",
    "S132": "Superman - Countdown to Apokolips (USA)",
    "S133": "Superman Returns - Fortress of Solitude (USA, Europe) (En,Fr,De,Es,It)",
    "S134": "Surf's Up (USA) (En,Fr,Es)",
    "S135": "Sword of Mana (USA, Australia)",
    "T001":	"TMNT (USA) (En,Fr,Es)",
    "T002":	"Tactics Ogre - The Knight of Lodis (USA)",
    "T003":	"Tak - The Great Juju Challenge (USA, Europe)",
    "T004":	"Tak 2 - The Staff of Dreams (USA)",
    "T005":	"Tak and the Power of Juju (USA)",
    "T006":	"Tales of Phantasia (USA, Australia)",
    "T007":	"Tang Tang (USA)",
    "T008":	"Tarzan - Return to the Jungle (USA, Europe)",
    "T009":	"Teen Titans (USA) (En,Fr)",
    "T010":	"Teen Titans 2 (USA) (En,Fr)",
    "T011":	"Teenage Mutant Ninja Turtles (USA)",
    "T012":	"Teenage Mutant Ninja Turtles 2 - Battle Nexus (USA)",
    "T013":	"Teenage Mutant Ninja Turtles Double Pack (USA) (En,Fr,De,Es,It)",
    "T014":	"Tekken Advance (USA)",
    "T015":	"Ten Pin Alley 2 (USA)",
    "T016":	"Terminator 3 - Rise of the Machines (USA)",
    "T017":	"Tetris Worlds (USA)",
    "T018":	"Texas Hold 'em Poker (USA, Europe)",
    "T019":	"That's So Raven (USA)",
    "T020":	"That's So Raven 2 - Supernatural Style (USA) (En,Fr)",
    "T021":	"Three-in-One Pack - Connect Four + Perfection + Trouble (USA)",
    "T022":	"Three-in-One Pack - Risk + Battleship + Clue (USA) (Rev 1)",
    "T023":	"Three-in-One Pack - Sorry! + Aggravation + Scrabble Junior (USA)",
    "T024":	"Three Stooges, The (USA)",
    "T025":	"Thunder Alley (USA)",
    "T026":	"Thunderbirds (USA, Europe)",
    "T027":	"Tiger Woods PGA Tour 2004 (USA, Europe)",
    "T028":	"Tiger Woods PGA Tour Golf (USA, Europe)",
    "T029":	"Tim Burton's The Nightmare Before Christmas - The Pumpkin King (USA, Europe) (En,Fr,De,Es,It)",
    "T030":	"Tiny Toon Adventures - Scary Dreams (USA)",
    "T031":	"Tiny Toon Adventures - Wacky Stackers (USA)",
    "T032":	"Tokyo Xtreme Racer Advance (USA)",
    "T033":	"Tom Clancy's Rainbow Six - Rogue Spear (USA) (En,Fr,De,Es,It)",
    "T034":	"Tom Clancy's Splinter Cell (USA) (En,Fr,Es)",
    "T035":	"Tom Clancy's Splinter Cell - Pandora Tomorrow (USA) (En,Fr,Es)",
    "T036":	"Tom and Jerry - The Magic Ring (USA) (En,Fr,De,Es,It)",
    "T037":	"Tom and Jerry Tales (USA) (En,Fr,Es)",
    "T038":	"Tom and Jerry in Infurnal Escape (USA)",
    "T039":	"Tonka - On the Job (USA)",
    "T040":	"Tony Hawk's American Sk8land (USA)",
    "T041":	"Tony Hawk's Downhill Jam (USA)",
    "T042":	"Tony Hawk's Pro Skater 2 (USA, Europe)",
    "T043":	"Tony Hawk's Pro Skater 3 (USA, Europe)",
    "T044":	"Tony Hawk's Pro Skater 4 (USA, Europe)",
    "T045":	"Tony Hawk's Underground (USA, Europe)",
    "T046":	"Tony Hawk's Underground 2 (USA, Europe)",
    "T047":	"Top Gear GT Championship (USA)",
    "T048":	"Top Gear Rally (USA)",
    "T049":	"Top Gun - Combat Zones (USA) (En,Fr,De,Es,It)",
    "T050":	"Top Gun - Firestorm Advance (USA, Europe) (En,Fr,De,Es,It)",
    "T051":	"Top Spin 2 (USA) (En,Fr,De,Es,It)",
    "T052":	"Totally Spies! (USA)",
    "T053":	"Totally Spies! 2 - Undercover (USA) (En,Fr)",
    "T054":	"Tower SP, The (USA)",
    "T055":	"Treasure Planet (USA)",
    "T056":	"Tringo (USA)",
    "T057":	"Trollz - Hair Affair! (USA)",
    "T058":	"Tron 2.0 - Killer App (USA)",
    "T059":	"Turbo Turtle Adventure (USA)",
    "T060":	"Turok - Evolution (USA)",
    "T061":	"Tweety and the Magic Gems (USA)",
    "T062":	"Ty the Tasmanian Tiger 2 - Bush Rescue (USA, Europe) (En,Fr,De)",
    "T063":	"Ty the Tasmanian Tiger 3 - Night of the Quinkan (USA)",
    "U001":	"Ultimate Arcade Games (USA)",
    "U002":	"Ultimate Beach Soccer (USA)",
    "U003":	"Ultimate Brain Games (USA, Europe)",
    "U004":	"Ultimate Card Games (USA) (Rev 2)",
    "U005":	"Ultimate Muscle - The Kinnikuman Legacy - The Path of the Superhero (USA)",
    "U006":	"Ultimate Puzzle Games (USA)",
    "U007":	"Ultimate Spider-Man (USA)",
    "U008":	"Ultimate Winter Games (USA)",
    "U009":	"Unfabulous (USA)",
    "U010":	"Uno 52 (USA)",
    "U011":	"Uno Free Fall (USA)",
    "U012":	"Urban Yeti! (USA, Europe)",
    "U013":	"Urbz, The - Sims in the City (USA, Europe) (En,Fr,De,Es,It,Nl)",
    "V001":	"V-Rally 3 (USA) (En,Fr,Es)",
    "V002":	"Van Helsing (USA)",
    "V003":	"VeggieTales - LarryBoy and the Bad Apple (USA)",
    "V004":	"Virtua Tennis (USA)",
    "V005":	"Virtual Kasparov (USA) (En,Fr,De,Es,It)",
    "W001":	"WTA Tour Tennis (USA)",
    "W002":	"WWE - Road to WrestleMania X8 (USA, Europe)",
    "W003":	"WWE - Survivor Series (USA, Europe)",
    "W004":	"WWF - Road to WrestleMania (USA, Europe)",
    "W005":	"Wade Hixton's Counter Punch (USA, Europe)",
    "W006":	"Wakeboarding Unleashed Featuring Shaun Murray (USA)",
    "W007":	"Wario Land 4 (USA, Europe)",
    "W008":	"WarioWare, Inc. - Mega Microgame$! (USA)",
    "W009":	"WarioWare - Twisted! (USA)",
    "W010":	"Whac-A-Mole (USA)",
    "W011":	"Wild, The (USA, Europe) (En,Fr,De,Es)",
    "W012":	"Wild Thornberrys, The - Chimp Chase (USA, Europe)",
    "W013":	"Wild Thornberrys Movie, The (USA, Europe)",
    "W014":	"WinX Club (USA)",
    "W015":	"WinX Club - Quest for the Codex (USA)",
    "W016":	"Wing Commander - Prophecy (USA)",
    "W017":	"Wings (USA)",
    "W018":	"Winnie the Pooh's Rumbly Tumbly Adventure (USA) (En,Fr,Es)",
    "W019":	"Wolfenstein 3D (USA, Europe)",
    "W020":	"Woody Woodpecker in Crazy Castle 5 (USA)",
    "W021":	"Word Safari - The Friendship Totems (USA)",
    "W022":	"World Championship Poker (USA)",
    "W023":	"World Poker Tour (USA)",
    "W024":	"World Tennis Stars (USA)",
    "W025":	"Worms World Party (USA) (En,Fr,De,Es,It)",
    "X001":	"X-Bladez - Inline Skater (USA)",
    "X002":	"X-Men - Reign of Apocalypse (USA, Europe)",
    "X003":	"X-Men - The Official Game (USA)",
    "X004":	"X2 - Wolverine's Revenge (USA, Europe)",
    "X005":	"XS Moto (USA)",
    "X006":	"xXx (USA, Europe)",
    "Y001":	"Yggdra Union - We'll Never Fight Alone (USA)",
    "Y002":	"Yoshi Topsy-Turvy (USA)",
    "Y003":	"Yu-Gi-Oh! - 7 Trials to Glory - World Championship Tournament 2005 (USA) (En,Ja,Fr,De,Es,It)",
    "Y004":	"Yu-Gi-Oh! - Destiny Board Traveler (USA)",
    "Y005":	"Yu-Gi-Oh! - Dungeon Dice Monsters (USA) (En,Es)",
    "Y006":	"Yu-Gi-Oh! - Reshef of Destruction (USA)",
    "Y007":	"Yu-Gi-Oh! - The Eternal Duelist Soul (USA)",
    "Y008":	"Yu-Gi-Oh! - The Sacred Cards (USA)",
    "Y009":	"Yu-Gi-Oh! - Ultimate Masters - World Championship Tournament 2006 (USA) (En,Ja,Fr,De,Es,It)",
    "Y010":	"Yu-Gi-Oh! - World Championship Tournament 2004 (USA) (En,Ja,Fr,De,Es,It)",
    "Y011":	"Yu-Gi-Oh! - Worldwide Edition - Stairway to the Destined Duel (USA) (En,Ja,Fr,De,Es,It)",
    "Y012":	"Yu-Gi-Oh! Double Pack (USA)",
    "Y013":	"Yu-Gi-Oh! Double Pack 2 (USA) (En,Fr,De,Es,It)",
    "Y014":	"Yu-Gi-Oh! GX - Duel Academy (USA)",
    "Y015":	"Yu Yu Hakusho - Ghostfiles - Spirit Detective (USA)",
    "Y016":	"Yu Yu Hakusho - Ghostfiles - Tournament Tactics (USA, Europe)",
    "Z001":	"Zapper - One Wicked Cricket! (USA)",
    "Z002":	"Zatchbell! - Electric Arena (USA)",
    "Z003":	"Zoey 101 (USA)",
    "Z004":	"Zoids Legacy (USA)",
    "Z005":	"Zone of the Enders - The Fist of Mars (USA)",
    "Z006":	"ZooCube (USA)",    
}